/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.opentext.bn.converters.avro.entity;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Destination extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -650911187281775503L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Destination\",\"namespace\":\"com.opentext.bn.converters.avro.entity\",\"fields\":[{\"name\":\"type\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"destinationKey\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Destination> ENCODER =
      new BinaryMessageEncoder<Destination>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Destination> DECODER =
      new BinaryMessageDecoder<Destination>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Destination> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Destination> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Destination>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Destination to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Destination from a ByteBuffer. */
  public static Destination fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.String type;
   private java.lang.String destinationKey;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Destination() {}

  /**
   * All-args constructor.
   * @param type The new value for type
   * @param destinationKey The new value for destinationKey
   */
  public Destination(java.lang.String type, java.lang.String destinationKey) {
    this.type = type;
    this.destinationKey = destinationKey;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return type;
    case 1: return destinationKey;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: type = (java.lang.String)value$; break;
    case 1: destinationKey = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public java.lang.String getType() {
    return type;
  }


  /**
   * Gets the value of the 'destinationKey' field.
   * @return The value of the 'destinationKey' field.
   */
  public java.lang.String getDestinationKey() {
    return destinationKey;
  }


  /**
   * Creates a new Destination RecordBuilder.
   * @return A new Destination RecordBuilder
   */
  public static com.opentext.bn.converters.avro.entity.Destination.Builder newBuilder() {
    return new com.opentext.bn.converters.avro.entity.Destination.Builder();
  }

  /**
   * Creates a new Destination RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Destination RecordBuilder
   */
  public static com.opentext.bn.converters.avro.entity.Destination.Builder newBuilder(com.opentext.bn.converters.avro.entity.Destination.Builder other) {
    return new com.opentext.bn.converters.avro.entity.Destination.Builder(other);
  }

  /**
   * Creates a new Destination RecordBuilder by copying an existing Destination instance.
   * @param other The existing instance to copy.
   * @return A new Destination RecordBuilder
   */
  public static com.opentext.bn.converters.avro.entity.Destination.Builder newBuilder(com.opentext.bn.converters.avro.entity.Destination other) {
    return new com.opentext.bn.converters.avro.entity.Destination.Builder(other);
  }

  /**
   * RecordBuilder for Destination instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Destination>
    implements org.apache.avro.data.RecordBuilder<Destination> {

    private java.lang.String type;
    private java.lang.String destinationKey;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.opentext.bn.converters.avro.entity.Destination.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.type)) {
        this.type = data().deepCopy(fields()[0].schema(), other.type);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.destinationKey)) {
        this.destinationKey = data().deepCopy(fields()[1].schema(), other.destinationKey);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Destination instance
     * @param other The existing instance to copy.
     */
    private Builder(com.opentext.bn.converters.avro.entity.Destination other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.type)) {
        this.type = data().deepCopy(fields()[0].schema(), other.type);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.destinationKey)) {
        this.destinationKey = data().deepCopy(fields()[1].schema(), other.destinationKey);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public java.lang.String getType() {
      return type;
    }

    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public com.opentext.bn.converters.avro.entity.Destination.Builder setType(java.lang.String value) {
      validate(fields()[0], value);
      this.type = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public com.opentext.bn.converters.avro.entity.Destination.Builder clearType() {
      type = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'destinationKey' field.
      * @return The value.
      */
    public java.lang.String getDestinationKey() {
      return destinationKey;
    }

    /**
      * Sets the value of the 'destinationKey' field.
      * @param value The value of 'destinationKey'.
      * @return This builder.
      */
    public com.opentext.bn.converters.avro.entity.Destination.Builder setDestinationKey(java.lang.String value) {
      validate(fields()[1], value);
      this.destinationKey = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'destinationKey' field has been set.
      * @return True if the 'destinationKey' field has been set, false otherwise.
      */
    public boolean hasDestinationKey() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'destinationKey' field.
      * @return This builder.
      */
    public com.opentext.bn.converters.avro.entity.Destination.Builder clearDestinationKey() {
      destinationKey = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Destination build() {
      try {
        Destination record = new Destination();
        record.type = fieldSetFlags()[0] ? this.type : (java.lang.String) defaultValue(fields()[0]);
        record.destinationKey = fieldSetFlags()[1] ? this.destinationKey : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Destination>
    WRITER$ = (org.apache.avro.io.DatumWriter<Destination>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Destination>
    READER$ = (org.apache.avro.io.DatumReader<Destination>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
