/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.opentext.bn.converters.avro.entity;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum NotificationType {
  DEFAULT_BUSINESS_POC, DEFAULT_SERVICE_POC, TRADING_PARTNER_POC, CONTACT_ID  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"NotificationType\",\"namespace\":\"com.opentext.bn.converters.avro.entity\",\"symbols\":[\"DEFAULT_BUSINESS_POC\",\"DEFAULT_SERVICE_POC\",\"TRADING_PARTNER_POC\",\"CONTACT_ID\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
